### ISSUE TITLE
Game randomly crashes

### ISSUE THREAD

**Issue by armn** [armn/sviests#1]
2019-05-09T20:40:09.361030+00:00 app[web.1]: /app/cah-server/index.js:181
2019-05-09T20:40:09.361041+00:00 app[web.1]:     const round = game.getRoundById(roundId);
2019-05-09T20:40:09.361043+00:00 app[web.1]:                        ^
2019-05-09T20:40:09.361044+00:00 app[web.1]: 
2019-05-09T20:40:09.361046+00:00 app[web.1]: TypeError: Cannot read property 'getRoundById' of undefined
2019-05-09T20:40:09.361048+00:00 app[web.1]:     at CahServer.playerSubmitted (/app/cah-server/index.js:181:24)
2019-05-09T20:40:09.361049+00:00 app[web.1]:     at emitMany (events.js:147:13)
2019-05-09T20:40:09.361051+00:00 app[web.1]:     at Socket.emit (events.js:224:7)
2019-05-09T20:40:09.361052+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:503:12
2019-05-09T20:40:09.361053+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2019-05-09T20:40:09.361054+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2019-05-09T20:40:09.375611+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-05-09T20:40:09.375968+00:00 app[web.1]: npm ERR! errno 1
2019-05-09T20:40:09.377020+00:00 app[web.1]: npm ERR! cah-game@1.0.0 start: `node server`
2019-05-09T20:40:09.377174+00:00 app[web.1]: npm ERR! Exit status 1
2019-05-09T20:40:09.377391+00:00 app[web.1]: npm ERR! 
2019-05-09T20:40:09.377556+00:00 app[web.1]: npm ERR! Failed at the cah-game@1.0.0 start script.
2019-05-09T20:40:09.377710+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-09T20:40:09.383236+00:00 app[web.1]: 
2019-05-09T20:40:09.383419+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:

**Comment by armn** [comment]
Added a check for roundId in https://github.com/armn/sviests/commit/5f2d762255dcd491917e895f451f6c15d1296081, server should no longer crash.
