### ISSUE TITLE
Crash on newMessage

### ISSUE THREAD

**Issue by armn** [armn/sviests#4]
2019-05-10T04:49:52.717483+00:00 app[web.1]: /app/cah-server/index.js:144
2019-05-10T04:49:52.717484+00:00 app[web.1]:     this.socket.room.newMessage({
2019-05-10T04:49:52.717486+00:00 app[web.1]:                      ^
2019-05-10T04:49:52.717487+00:00 app[web.1]: 
2019-05-10T04:49:52.717489+00:00 app[web.1]: TypeError: Cannot read property 'newMessage' of undefined
2019-05-10T04:49:52.717490+00:00 app[web.1]:     at CahServer.sendChat (/app/cah-server/index.js:144:22)
2019-05-10T04:49:52.717492+00:00 app[web.1]:     at emitTwo (events.js:126:13)
2019-05-10T04:49:52.717493+00:00 app[web.1]:     at Socket.emit (events.js:214:7)
2019-05-10T04:49:52.717494+00:00 app[web.1]:     at /app/node_modules/socket.io/lib/socket.js:503:12
2019-05-10T04:49:52.717496+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2019-05-10T04:49:52.717497+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2019-05-10T04:49:52.728520+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-05-10T04:49:52.728797+00:00 app[web.1]: npm ERR! errno 1
2019-05-10T04:49:52.729857+00:00 app[web.1]: npm ERR! cah-game@1.0.0 start: `node server`
2019-05-10T04:49:52.729965+00:00 app[web.1]: npm ERR! Exit status 1
2019-05-10T04:49:52.730129+00:00 app[web.1]: npm ERR! 
2019-05-10T04:49:52.730240+00:00 app[web.1]: npm ERR! Failed at the cah-game@1.0.0 start script.
2019-05-10T04:49:52.730352+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-05-10T04:49:52.736836+00:00 app[web.1]: 
2019-05-10T04:49:52.737026+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-05-10T04:49:52.737164+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-05-10T04_49_52_731Z-debug.log

**Comment by armn** [comment]
Should be fixed with https://github.com/armn/sviests/commit/6716b1fbeddcb302064dbb50103ddbbdca5a1351
